/* Auto-generated by build-search-index.mjs — do not edit */
window.GUIDE_SEARCH_INDEX = [
  {
    "file": "layout.html",
    "title": "Design Tokens",
    "sections": [
      {
        "section": "Color Tokens",
        "sectionId": "color-tokens",
        "text": "Neutral surfaces, accent palette, status indicators, and text hierarchy. Color Tokens Backgrounds Primary Accent Secondary Accent Status Text Borders Terminal"
      },
      {
        "section": "Browse and explore agent recordings",
        "sectionId": "browse-and-explore-agent-recordings",
        "text": "Minor Third (1.2) modular scale from 14px base. Geist for UI, Geist Mono for code. Browse and explore agent recordings Type Scale {{ t.token }} {{ t.value }} Line Height {{ lh.label }} {{ lh.token }} {{ lh.value }} — {{ lh.usage }} Letter Spacing {{ ls.label }} {{ ls.token }} {{ ls.value }} Font Weights Font Families Type in Context Terminal Sessions, Unfolded Browse and explore agent recordings Erika transforms raw terminal sessions into navigable, searchable documents. Upload a .cast file and the system detects sections, highlights markers, and makes every keystroke findable. Last updated 2 hours ago · 1,247 events · 23 sections detected"
      },
      {
        "section": "Spacing Tokens",
        "sectionId": "spacing-tokens",
        "text": "4px base grid. All spacing values derived from a consistent scale. Spacing Tokens"
      },
      {
        "section": "Layout Tokens",
        "sectionId": "layout-tokens",
        "text": "Container sizing, grid gaps, breakpoints, and component height scale. Layout Tokens Layout Tokens --container-max 960px Max content width for centered layouts --container-padding var(--space-6) Side padding for content container --grid-gap var(--space-4) Default gap between grid items --header-height 56px Fixed app header height Grid Classes These utility classes live in shared/layout.css and are available to all stages. Apply .grid as the base class for display: grid and gap, then add a modifier like .grid--sidebar to set the column template. All multi-column grids collapse to a single column below 768px. Breakpoints Component Heights"
      },
      {
        "section": "Shape Tokens",
        "sectionId": "shape-tokens",
        "text": "Border radii from subtle rounding to fully circular, plus elevation shadows. Shape Tokens Border Radius Shadows"
      },
      {
        "section": "Animation Tokens",
        "sectionId": "animation-tokens",
        "text": "Timing and easing for transitions. Hover the boxes to preview each duration. Animation Tokens"
      },
      {
        "section": "CSS Custom Properties Map",
        "sectionId": "css-custom-properties-map",
        "text": "Complete mapping of token names to values and intended usage. CSS Custom Properties Map Token Value Usage"
      },
      {
        "section": "CSS Classes",
        "sectionId": "css-classes",
        "text": "Reusable classes from layout.css, components.css, and page.css. These consume design tokens — use them directly on HTML elements. CSS Classes Class CSS Output Usage"
      }
    ]
  },
  {
    "file": "components.html",
    "title": "Component Library",
    "sections": [
      {
        "section": "1. Card (Base)",
        "sectionId": "1-card-base",
        "text": "1. Card (Base) 1. Card (Base) Foundational surface container. Four modifiers and structured children (.card__title, .card__label, .card__value, .card__desc, .card__body, .card__media). .card — Default --space-5 padding Column layout, radius-xl. The standard container for grouped content. --space-3 / --space-4 .card--compact Tighter padding, smaller radius. For dense lists and token grids. Leading Whitespace Detection 12 sections · 8m 34s Normal --duration-normal 250ms Media Card --accent-primary #00ff9f Terminal BG --terminal-bg #1e1e22 Gradient Custom media Full-bleed visual area Cards compose with child classes. Session Card extends this base. Sessions 127 Total Duration 48h 12m"
      },
      {
        "section": "2. Button",
        "sectionId": "2-button",
        "text": "2. Button 2. Button Outlined buttons with fill-on-hover. Four variants, two sizes, five states each."
      },
      {
        "section": "3. Input",
        "sectionId": "3-input",
        "text": "3. Input 3. Input Text inputs with label, helper text, and error messaging. Also textarea variant."
      },
      {
        "section": "4. Badge",
        "sectionId": "4-badge",
        "text": "4. Badge 4. Badge Pill-shaped labels for status, agent types, and metadata. Default and small sizes."
      },
      {
        "section": "5. Session Card",
        "sectionId": "5-session-card",
        "text": "5. Session Card 5. Session Card Primary list item. Shows session metadata with agent badge, timestamp, and metrics."
      },
      {
        "section": "6. Toast / Notification",
        "sectionId": "6-toast-notification",
        "text": "6. Toast / Notification 6. Toast / Notification Transient notifications with left accent border. Four semantic variants with close button."
      },
      {
        "section": "7. AppHeader",
        "sectionId": "7-appheader",
        "text": "7. AppHeader 7. AppHeader Top navigation bar with brand, navigation links, upload action, and user avatar."
      },
      {
        "section": "8. Search Bar",
        "sectionId": "8-search-bar",
        "text": "8. Search Bar 8. Search Bar Search input with icon, placeholder, clear button, and results count."
      },
      {
        "section": "9. Upload Zone",
        "sectionId": "9-upload-zone",
        "text": "9. Upload Zone 9. Upload Zone Drag-and-drop area with five distinct states: default, drag-over, uploading, success, and error."
      },
      {
        "section": "10. Section Header",
        "sectionId": "10-section-header",
        "text": "10. Section Header 10. Section Header Collapsible section headers for the terminal document view. Detected vs Marker distinction via left accent border."
      },
      {
        "section": "11. Modal Shell",
        "sectionId": "11-modal-shell",
        "text": "11. Modal Shell 11. Modal Shell Overlay container with header, scrollable body, and footer action area. Upload Session"
      },
      {
        "section": "12. Empty State",
        "sectionId": "12-empty-state",
        "text": "12. Empty State 12. Empty State Placeholder for when no sessions exist. Personality-driven copy with call to action. No sessions yet Your terminal recordings will show up here. Drop a .cast file to get started, or record a session with AGR."
      },
      {
        "section": "13. Skeleton Loader",
        "sectionId": "13-skeleton-loader",
        "text": "13. Skeleton Loader 13. Skeleton Loader Loading placeholders for cards and content. Subtle shimmer animation."
      },
      {
        "section": "14. Dropdown / Select",
        "sectionId": "14-dropdown-select",
        "text": "14. Dropdown / Select 14. Dropdown / Select Custom select with label, options list. Five states: default, open, focused, disabled, error.\n          Options support optional icons via .dropdown__icon and group headings via .dropdown__group-label."
      },
      {
        "section": "15. Date Input",
        "sectionId": "15-date-input",
        "text": "15. Date Input 15. Date Input Styled date input with label. States: default, focused, with value, disabled, error."
      },
      {
        "section": "16. Email Input",
        "sectionId": "16-email-input",
        "text": "16. Email Input 16. Email Input Email-specific input with inline validation feedback. States: default, focused, valid, invalid, disabled."
      },
      {
        "section": "17. Terminal Chrome",
        "sectionId": "17-terminal-chrome",
        "text": "17. Terminal Chrome 17. Terminal Chrome Container frame for terminal content. Title bar with faux traffic lights, monospace content area."
      },
      {
        "section": "18. Breadcrumb",
        "sectionId": "18-breadcrumb",
        "text": "18. Breadcrumb 18. Breadcrumb Navigation breadcrumb for session detail pages."
      },
      {
        "section": "19. Previous / Next Navigation",
        "sectionId": "19-previous-next-navigation",
        "text": "19. Previous / Next Navigation 19. Previous / Next Navigation Session-to-session navigation controls with disabled state for first/last."
      },
      {
        "section": "20. Filter Pills",
        "sectionId": "20-filter-pills",
        "text": "20. Filter Pills 20. Filter Pills Agent type filter pills for session search. Adjacent to search bar."
      },
      {
        "section": "21. Spinners & Loaders",
        "sectionId": "21-spinners-loaders",
        "text": "21. Spinners & Loaders 21. Spinners & Loaders Loading indicators for every context — inline actions, section loads, full-page transitions, and the branded matrix effect."
      },
      {
        "section": "22. Session Viewer (Composition)",
        "sectionId": "22-session-viewer-composition",
        "text": "22. Session Viewer (Composition) 22. Session Viewer (Composition) Composition of terminal chrome, section headers, badges, and buttons into the session document viewer. Not a new component — orchestrates existing primitives."
      }
    ]
  },
  {
    "file": "iconography.html",
    "title": "Iconography",
    "sections": [
      {
        "section": "Size Classes Reference",
        "sectionId": "size-classes-reference",
        "text": "Size Classes Reference Size Classes Reference Icon sizes are mapped to spacing tokens. Each size class applies a fixed width and height. All mask-image SVGs share a 20x20 viewBox for consistent scaling. Class Size Token Usage .icon--xs 12px --space-3 Inline with small text .icon--sm 16px --space-4 Badges, small buttons, inline .icon--md 20px --space-5 Default, most components .icon--lg 24px --space-6 Upload zone, empty state .icon--xl 32px --space-8 Hero, feature icons .icon--2xl 48px --space-12 Splash, loading states"
      },
      {
        "section": "{{ groupLabels[groupName] }}",
        "sectionId": "grouplabels-groupname",
        "text": "{{ groupLabels[groupName] }} {{ groupLabels[groupName] }} {{ groupDescriptions[groupName] }} Name xs (12) sm (16) md (20) lg (24) xl (32) {{ icon.name }}\n                {{ icon.usage }}"
      },
      {
        "section": "Color Inheritance",
        "sectionId": "color-inheritance",
        "text": "Color Inheritance Color Inheritance Icons use background: currentColor with CSS mask-image to inherit the parent element's text color. Any CSS color value propagates through the icon."
      },
      {
        "section": "Typography Baseline Match",
        "sectionId": "typography-baseline-match",
        "text": "Typography Baseline Match Typography Baseline Match Icons sized to sit inline with text at each type scale step. The icon height matches the computed line height of its paired text, keeping vertical rhythm."
      }
    ]
  }
];
